UpdateStatus/urls.py
from django.conf.urls import url
from .views import index, update_status

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', update_status, name='add_status'),   
]

addFriend/urls.py
from django.conf.urls import url
from .views import index, addFriend, delete_friend
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'addFriend/', addFriend, name='addFriend'),
    url(r'^delete/(?P<pk>\d+)/$', delete_friend, name='delete_friend')

]

gitrekt/urls.py
from django.views.generic.base import RedirectView
from django.conf.urls import url, include
from django.contrib import admin

import profile_page.urls as profile_page
import stats.urls as stats
import addFriend.urls as friend
import UpdateStatus.urls as status
from UpdateStatus.views import index as index_status


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(profile_page, namespace='profile')),
    url(r'^stats/', include(stats, namespace='stats')),
    url(r'^friend/', include(friend, namespace='friend')),
    url(r'^status/', include(status,namespace='status')),
    url(r'^$', index_status, name='index'),
]

profile_page/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

stats/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

UpdateStatus/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    message = models.TextField()
    # 
    # def __str__(self):
    # 	return self.messages

addFriend/models.py
from django.db import models

# Create your models here.
class Friends(models.Model):
    name = models.CharField(max_length=60)
    url = models.URLField()
    created_date = models.DateTimeField(auto_now_add=True)

profile_page/models.py
from django.db import models

class Expertise(models.Model):
    name = models.TextField()

class Profile(models.Model):
    image = models.ImageField()
    name = models.CharField(max_length=27)
    birthday = models.DateTimeField()
    gender = models.TextField()
    expertise = models.ManyToManyField(Expertise)
    description = models.TextField()
    email = models.EmailField()

stats/models.py
from django.db import models

# Create your models here.

UpdateStatus/forms.py
from django import forms

class Status_Form(forms.Form):
	error_messages = {
		'required': 'Please fill in the input',
	}
	attrs = {
		'class': 'form-control',
		'rows':4,
		'cols':10,
		'style':'width:85%;',
	}

	status = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True, label="")

addFriend/forms.py
from django import forms
from django.test import TestCase
from django.test import Client
from django.urls import resolve
from django.http import HttpRequest
from .models import Friends

class Friend_Form(forms.Form):

    name = forms.CharField(label='Nama', required=True, max_length=30,)
    url = forms.URLField(label = 'URL', required=True)

    def clean(self):
        cleaned_data = super(Friend_Form, self).clean()
        name = cleaned_data.get("name")
        data = cleaned_data.get("url")
        response = Client().get(data)
        html_response = response.content.decode('utf8')
        if "herokuapp.com" not in data or response.status_code == 404:
            raise forms.ValidationError("HerokuApp does not exist")

UpdateStatus/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Status
from .forms import Status_Form
from profile_page.models import Profile

response = {'author': "gitgud"}

def index(request):
	response['Status_Form'] = Status_Form
	status = Status.objects.all()
	profile = Profile.objects.all()
	response['status'] = status
	response['profile'] = profile
	return render(request, 'update_status.html', response)

def update_status(request):
	form = Status_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['status'] = request.POST['status']
		status = Status(message=response['status'])
		status.save()
		return HttpResponseRedirect('/status/')
	else:
		return HttpResponseRedirect('/status/')

addFriend/views.py
from django.shortcuts import render, redirect
from .models import Friends
from .forms import Friend_Form

def index(request):
    response = {}
    html = 'add_friend.html'
    response['Friend_Form'] = Friend_Form
    friend = Friends.objects.all()
    response['friends'] = friend
    return render(request, html , response)

def addFriend(request):
    response = {}
    form = Friend_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['url'] = request.POST['url']
        friend = Friends(name=form.cleaned_data['name'], url=form.cleaned_data['url'])
        friend.save()
    else:
        response['form'] = form
    html ='add_friend.html'
    friend = Friends.objects.all()
    response['friends'] = friend
    return render(request, html, response)

def delete_friend(request, pk):
    todo = Friends.objects.filter(pk=pk).first()
    todo.delete()
    return HttpResponseRedirect('/friend/')

profile_page/views.py
from django.shortcuts import render
from .models import Profile, Expertise

# expertise = Expertise(name='Singer')
# expertise1 = Expertise(name='Songwriter')
# expertise2 = Expertise(name='Actor')
# expertise.save()
# expertise1.save()
# expertise2.save()
# new_profile = Profile.objects.create(id=2, image='David-Bowie.jpg', name='David Bowie', birthday='1947-01-08 14:14:00', gender='Male', description='Ziggy Stardust', email='david@bowie.com')
# new_profile.expertise.add(expertise, expertise1, expertise2)

response = {}
def index(request):
    profile = Profile.objects.all()
    response['author'] = "gitgud"
    response['profile'] = profile
    return render(request, 'profile_page.html', response)

# {{ profile.date | date:"d.m.Y" }} >> bisa pake kayak gini di htmlnyaa


# Profile(name='Test', birthday=, gender='Male', description='Free rider', email='hello@gmail.com')
# profile.save()
#
# expertise1 = Expertise(name='Marketing')
# expertise2 = Expertise(name='Collector')
# expertise3 = Expertise(name='Public Speaking')
# expertise1.save()
# expertise2.save()
# expertise3.save()
#
# profile.expertise.add(expertise1)
# profile.expertise.add(expertise2)
# profile.expertise.add(expertise3)

stats/views.py
from django.shortcuts import render
from profile_page.models import Profile, Expertise
from addFriend.models import Friends
from UpdateStatus.models import Status

response = {}
def index(request):
    profile = Profile.objects.all()
    friends = Friends.objects.all().count()
    status = Status.objects.all().count()
    try:
        latest = Status.objects.latest('date')
    except Status.DoesNotExist:
        latest = None
    response['author'] = "gitgud"
    response['profile'] = profile
    response['friend'] = friends
    response['status'] = status
    response['latest'] = latest
    return render(request, 'stats.html', response)

UpdateStatus/templates/update_status.html
{% extends "layout/base.html" %}
{% block content %}
<head>
    <meta name="description" content="Profile Page">
    <title>
        {% block title %} Update Status by {{author}} {% endblock %}
    </title>
</head>
<div class='wrapper'>
<section style="margin-left:10%">
<section name="update_status">
    <h2>Update Status</h2>
    <form id="form" method="POST" action="{% url 'status:add_status' %}">
        {% csrf_token %}
        {{ Status_Form }}
        <br>
        <button type="submit" class="btn btn-default">Post</button>
        <br/>
        <br/>
    </form>
</section>
<section name="status">
    {% if status %}
    {% for i in status reversed%}
    <table>
        <tr>
            {% for data in profile %}
            <td class='status-table'> <h4> {{data.name}} </h4> </td>
            {% endfor %}
        <tr>
            <td class='status-table'> {{i.message}} </td>
        </tr>
        <tr>
            <td class='status-table'> {{i.date}} </td>
        </tr>
    </table>
    <br/>
    {% endfor %}
    {% else %}
    {% endif %}

</section>
</section>
<hr/>
</div>
{% endblock %}

addFriend/templates/add_friend.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% load static %}

{% block content %}
<head>
    <meta name="description" content="Profile Page">
    <title>
        {% block title %} Add Friend by {{author}} {% endblock %}
    </title>
</head>
<div class='wrapper'>
<body class='body-addfriend'>
<style>
    #button {
        -webkit-transition-duration: 0.4s;
        transition-duration: 0.4s;
    }

    #button:hover {
        background-color: #82ABDC;
        color: white;
    }
    input[type=text] {
    width: 100%;
    padding: 12px 20px;
    box-sizing: border-box;
    border: 1px solid Black;
    border-radius: 12px;
    color: black;
    }
    input[type=text]:focus {
    border: 3px solid #555;
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-sm-7">
            <h1> Add Friend </h1>
            <form method="POST" action="{% url 'friend:addFriend' %}">
            {% csrf_token %}
            <div class="card">
                <div class="card-block">
                    <h5 class="card-title"> Name </h5>
                        <input type="text" class="form-control" name="name" id="name" required="required"/>
                    <h5 class="card-title"> URL </h5>
                        <input type="text" class="form-control" name="url" id="url" required="required"/>
                </div>
            </div>
            <button type="submit" class="btn btn-primary float-right" id="button">Add Friend</button>
            </form>
        </div>
        <div class="sol-sm-5">
        </div>
    </div>
</div>

<div class="row">
    <div class = container>
        <div class="flex">
            {% if friends %}
                {% for data in friends reversed %}
                    <div class="flex-item">
                        <div class="friend">
                            <div class="friend-name">
                                {{data.name}}
                            </div>
                            <div class="friend-date-added">
                                {{data.created_date}}
                            </div>
                            <div class="friend-url">
                                <a href="{{ data.url }}">{{data.url}}</a>
                            </div>
                            <div class="friend-delete">
                                <div class="friend-delete-button" data-id="{{data.id}}">Delete</div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Empty</strong>
            </div>
            {% endif %}
        </div>
    </div>
</div>

<script type="application/javascript">
    $(function() {
        $('.friend-delete-button').click(function() {
            var id = $(this).data('id')
            location.href = "/friend/delete/" + id + "/"
        });
    });
    </script>

    <!-- List all previous status -->
    <div class="container stasuses">
        {% for i in status reversed %}
            <div class="flex-item">
                <h5> {{ i.user.name }} </h5>
                {{ i.friend }} <br/>
                <sub> {{ i.date }} </sub>
            </div>
        {% endfor %}
    </div>
<br>
<br>
</body>
</div>
{% endblock %}

profile_page/templates/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/universal.css' %}" />
</head>

<body>
    <header>
        {% include "partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>
</body>
</html>

profile_page/templates/partials/footer.html
<!-- templates/lab_5/partials/footer.html -->
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -->
<p style='font-size: 80%'>Made by Kiki, Rasyid, Aghnia</p>

profile_page/templates/partials/header.html
{% load staticfiles %}
{% load static %}
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-static-top">
 <div class="container">
   <div class="navbar-header">
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
       <span class="sr-only">Toggle navigation</span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
     </button>
     <a class="navbar-brand" href="{% url 'status:index' %}">Gitrekt</a>
   </div>
   <div id="navbar" class="navbar-collapse collapse" style='float:right'>
     <ul class="nav navbar-nav">
       <li class="dropdown" style='float:right'>
           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
           <img src="{% static 'David-Bowie.jpg' %}" class="profile-image img-circle" style='height:30px;width:30px'>   <b class="caret"></b></a>
           <!-- <button class="dropbtn">Dropdown
             <b class="caret"></b></i>
           </button> -->
           <div class="dropdown-content">
             <a href="{% url 'profile:index' %}">Profile</a>
             <a href="{% url 'stats:index' %}">Stats</a>
           </div>
       </li>
       <li style='float:right'><a href="{% url 'friend:index' %}">Friend</a></li>
       <li style='float:right'><a href="{% url 'status:index' %}">Status</a></li>
     </ul>
   </div><!--/.nav-collapse -->
 </div>
</nav>

profile_page/templates/profile_page.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
<head>
    <meta name="description" content="Profile Page">
    <title>
        {% block title %} Profile Page by {{author}} {% endblock %}
    </title>
</head>
<div class='wrapper'>
<h4 class="main-title">Profile</h4>
{% for data in profile %}
<div class="content-wrapper">
    <br/>
    <br/>
    <section class="profile-header">
        <img class="img-circle" src="{% static 'David-Bowie.jpg' %}" style="height:120px;widht:120px">
        <h3>{{ data.name }}</h3>
    </section>
    <br/>
    <br/>
    <section class="section-profile-table">
    <div class="profile-table">
        <table align="left" style="text-align: left">
            <tr>
                <td>Birthday</td>
                <td>{{ data.birthday | date:"M d" }}</td>
            </tr>
            <tr>
                <td>Gender</td>
                <td>{{ data.gender }}</td>
            </tr>
            <tr>
                <td>Expertise</td>
                <td>
                {% for expertise in data.expertise.all %}
                    <div class="expertise">
                        {{ expertise.name }}
                    </div>
                {% endfor %}
                </td>
            </tr>
                <td>Description</td>
                <td>{{ data.description }}</td>
            </tr>
            <tr>
                <td>Email</td>
                <td>{{ data.email }}</td>
            </tr>
        </table>
    </div>
    </section>
</div>
{% endfor %}
</div>
{% endblock %}

stats/templates/stats.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
<head>
    <meta name="description" content="Statistics Page">
    <title>
        {% block title %} Dashboard by {{author}} {% endblock %}
    </title>
</head>
<div class='wrapper'>
<h4 class="main-title">Statistic</h4>
{% for data in profile %}
<div class="content-wrapper">
    <div class='flex' id='stats-div-header'>
    <section class='stats-header'>
        <img class='img-circle-stats' src="{% static 'David-Bowie.jpg' %}" style="height:120px;widht:120px">
        <h2 class="stats-name">{{ data.name }}</h2>
    </section>
    </div>
    <section class=section-stats-table>
    <div class=stats-table>
        <div class=friend-table>
            <table align="left" style="text-align: left">
                <tr>
                    <td>Friends</td>
                    <td>{{ friend }}</td>
                </tr>
                <tr>
                    <td>Feed</td>
                    <td>{{ status }}</td>
                </tr>
            </table>
        </div>
        <div class=latest-table>
            <table align="left" style="text-align: left">
                <tr>
                    <td>Latest Post</td>
                </tr>
                <tr>
                    <td>
                    {% if latest %}
                    <div class="box">
                        <ul id="first-list">
                            <li>
                                <span></span>
                                <div class="title">{{ latest.date }}</div>
                                <div class="info">{{ latest.message }}</div>
                            </li>
                        </ul>
                    </div>
                    {% else %}
                    <div class="box">
                        <ul id="first-list">
                            <li>
                                <span></span>
                                <div class="info">None.</div>
                            </li>
                        </ul>
                    </div>
                    {% endif %}
                    </td>
                </tr>

            </table>
        </div>
    </div>
    </section>
</div>
{% endfor %}
</div>
{% endblock %}

templates/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Profile Page">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/lab_5.css' %}" />


    <title>
        {% block title %} Profile Page By {{author}} {% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}

        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>
</body>
</html>

templates/footer.html
<!-- templates/lab_5/partials/footer.html -->
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -->
<p>Made with Love by {{author}}</p>

templates/header.html
<nav>
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!-- LINK INTO table, and link into home#form -->

        <li><a href="{% url 'profile:index' %}">Profile</a></li>
        >
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>